---
title: "Summary: Cycling Data"

date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_document

params:
    sample: sample
---

```{r setup, include = FALSE}
#library(knitr)
library(kableExtra)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(bat2dat)

#knitr::opts_chunk$set(cache=TRUE,
                   #   echo = TRUE)
 # fig.width = 6,
 # fig.asp = 0.8,
 # out.width = "80%"

#RMarkdown Cookbook: https://bookdown.org/yihui/rmarkdown-cookbook/kable.html#customize-html-tables
#RMArkdown References https://www.rstudio.com/wp-content/uploads/2015/03/rmarkdown-reference.pdf
#RMarkdown "The definite Guide" https://bookdown.org/yihui/rmarkdown/

```

```{r, include = FALSE}
cell <- params$sample

meta <- cell$metadata
capa <- cell$capacity

CYC <- plotGC(cell)
IR <- plotIRdrop(cell)
IntR <- plotIntR(cell)
VP <- plotVP(cell)
dQdV <- plotdQdV(cell)
dVdQ <- plotdVdQ(cell)

```

## Metadata & Cell Stats in brief {.tabset .tabset-fade .tabset-pills}
### Metadata
```{r metadata, echo = FALSE}

kableExtra::kable(t(meta), align = "cccc",
              #col.names = c("sample name",
               #              "active material loading [mg]",
                #              "cell type",
                 #            "battery cycler"),
      caption="Sample Infos") %>% 
      kableExtra::kable_styling(bootstrap_options = "striped", full_width = FALSE,  position="center")
# Error message: UseMethod("filter") no applicable method for 'filter'
# ignore. disappears in actual execution, when cap is defined
```

### Cell Stats @ 80%
```{r KPI, echo = FALSE}

ret <- dplyr::filter(capa, Qdc.mAh > Qdc.mAh[1]*0.8) 
if(nrow(ret) == 0) ret = head(capa,2)

keypara <- data.frame('max cycle number' = max(capa$CycNr)+1,
                      #'capacity retention' = tail((ret$CycNr),1),
                      'mean_Qch' = mean(ret$Qch.mAh.g),
                      'mean_Qdc' = mean(ret$Qdc.mAh.g),
                      'median_Qdc' = median(ret$Qdc.mAh.g)
                      )
kableExtra::kable(t(keypara), align = "cccc", digits = 2,
      caption="Cell Stats @ 80% capacity loss") %>% 
      kableExtra::kable_styling(bootstrap_options = "striped", full_width = FALSE, position = "center")


```

### Data Table
```{r initial.stats, echo = FALSE, message = FALSE}

max.cyc <- max(capa$CycNr)
cycles <- c(1:9, seq(10, max.cyc, max.cyc/10))

init.stats <- capa %>%
              dplyr::select(CycNr, Qch.mAh.g, Qdc.mAh.g, CE) %>%
              dplyr::filter(CycNr %in% cycles) %>% 
              dplyr::mutate(retetion = Qdc.mAh.g/Qdc.mAh.g[1]) 

kableExtra::kable(init.stats,
                  align = "cccc", digits = 2,
                  col.names = c("Cycle Number",
                                "Charge Capacity",
                                "Discharge Capacity",
                                "Coulombic Efficiency",
                                "Capacity Retention, discharge"),
                  caption="Initial Cycling Parameters") %>%
                  kableExtra::kable_styling(bootstrap_options = "striped", full_width = FALSE, position="center")

```


## Galvanostatic Cycling {.tabset .tabset-fade .tabset-pills}

### Capacity & CE Plots
```{r fig1, echo = FALSE, fig.height=5, fig.asp='.75', fig.align="center", fig.show="hold", results='asis', message=FALSE}

print(CYC$capa)
print(CYC$CE)

```

### IR drop
```{r fig2, echo = FALSE, message = FALSE, fig.height=4, fig.asp='0.75', fig.align="center", fig.show="hold", results='asis'}
#dev.off()

plot(IR$ch.drop)
plot(IR$dc.drop)
```

### Internal Resistance
```{r fig3, echo = FALSE, message = FALSE, fig.height=4, fig.asp='0.75', fig.align="center", fig.show="hold", results='asis'}

print(IntR$IntR.ch)
print(IntR$IntR.dc)
```

### CCCV
```{r fig4, echo = FALSE, message = FALSE, fig.height=5, fig.asp='0.75', fig.align="center", fig.show="hold", results='asis'}

print('coming soon')
```


## Voltage Profiles {.tabset .tabset-fade .tabset-pills}
### Looped
```{r fig5, echo = FALSE, message = FALSE, fig.height=6, fig.width=10, fig.align="center", results='asis'}

print(VP$VPloop)

```

### Linear
```{r fig6, echo = FALSE, message = FALSE, fig.height=6, fig.width=12, fig.align="center", results= 'asis', warning=FALSE}

print(VP$VPlin)

```

### Split
```{r fig7, echo = FALSE, message = FALSE, fig.height=5, fig.asp='2.0', fig.align="center", fig.show="hold", out.height='75%', results = 'asis', warning=FALSE}

print(VP$VPsplit.ch)
print(VP$VPsplit.dc)

```

## {-}
